### ISSUE TITLE
Is there any reason to specific version of requests library?

### ISSUE THREAD

**Issue by kiddick** [prawn-cake/vk-requests#12]
https://github.com/prawn-cake/vk-requests/blob/master/requirements.txt#L1

**Comment by prawn-cake** [comment]
Not really

**Comment by kiddick** [comment]
@prawn-cake I guess you need to set smth like requests>=2.8.1
Because with current setting it is downgrading requests according to requirements

**Comment by prawn-cake** [comment]
@kiddick good point, I'll fix it soon

**Comment by prawn-cake** [comment]
Updated at [v0.9.6](https://github.com/prawn-cake/vk-requests/tree/0.9.6)
