### ISSUE TITLE
Вопрос с wall.get

### ISSUE THREAD

**Issue by Ahellko** [prawn-cake/vk-requests#18]
Раньше используя api.wall.get я получал нужный пост со всем содержимым, но теперь при его использовании получаешь лишь словарь с пустым items

> {'items': [], 'count': 0}

Его теперь нужно использовать с ключом?

**Comment by prawn-cake** [comment]
Для доступа к api vk.com лучше всегда использовать аутентифицированный инстанс, т.е используя vk-requests это выглядит так
`api = vk_requests.create_api(app_id=123, login='User', password='Password')`

Так же версии vk.com api вводят некоторые изменения в форматах данных, сейчас на все (или на большинство) запросы возвращается словарь с ключами `items` и `count`. Здесь лучше проверять официальную документацию самого api

**Comment by Ahellko** [comment]
Ясно, спасибо за инфу
