### ISSUE TITLE
Example of get_captcha_key method reloading

### ISSUE THREAD

**Issue by RichardVoid** [prawn-cake/vk-requests#2]
I'm new to Python and do not quite understand how I have to reload this method in my code to handle captcha. It would be nice to see an example.

**Comment by prawn-cake** [comment]
The `get_captcha_key` is a part of `BaseAuthAPI` sub-classes which are part of `VKSession` namely `VKSession.AUTH_API_CLS` class variable.

To override the method you need:
* Create your own AuthAPI class derived from `BaseAuthAPI`, implement your getting captcha logic there
* Override `VKSession` with a new `AUTH_API_CLS` value
```
class MyAuthAPI(BaseAuthAPI):
    def get_captcha_key(self):
        # do something

class MyVKSession(VKSession):
    AUTH_API_CLS = MyAuthAPI


# Copied from create_api method
session = MyVKSession(app_id, login, password, phone_number=phone_number,
                                       scope=scope, api_version=api_version)
api = API(session=session, timeout=timeout, **method_default_args)
```

Well, I see that it's a bit hassle to do it and adding `auth_api_cls` as an instance parameter would be reasonable. I will think about it

**Comment by RichardVoid** [comment]
Thanks a lot.
