### ISSUE TITLE
Как авторизоваться по access token?

### ISSUE THREAD

**Issue by NinoZombie** [prawn-cake/vk-requests#20]
Собсно сабж :)
Или только по логину/паролю?

**Comment by prawn-cake** [comment]
[Access token](https://vk.com/dev/access_token) - это результат oauth аутентификации (которая предусматривает передачу логина и пароля).
Изначально было задумана, что библиотека должна заботиться об oauth. Использование стороннего токена (например, если пользователь хочет получить токен как-то по своему и затем использовать его) не предусмотрено, хотя пользователь всегда может пропатчить API класс. 
Но я бы не рекомендовал =)
