### ISSUE TITLE
Как получить текст сообщения?

### ISSUE THREAD

**Issue by RussianButman** [prawn-cake/vk-requests#21]
С помощью кода
`readmes = api.messages.get(out=0, count=1, time_offset = 1000)`
`readmesbody = readmes['items']`

я получаю
 `[{'id': 7275, 'date': 1495761621, 'out': 0, 'user_id': 326750873, 'read_state': 0, 'title': ' ... ', 'body': 'сообщение'}]`

Вопрос: как мне отсюда извлечь body?

**Comment by Ahellko** [comment]
Там пустой словарь по идее так что: readmes['items'][0]['body'].

Сорре за оффтоп, @prawn-cake, есть ли какой метод чтобы узнать наличествует ли в группе закрепленный пост?

**Comment by prawn-cake** [comment]
@RussianButman 
Ключ `items` содержит лист сериализованных в json [объектов](https://vk.com/dev/objects) (преобразованных в python dict библиотекой). Поэтому как верно заметил @Ahellko, нужно их вытаскивать из листа.

Если нужно получать список body, то я бы сделал так
```
resp = api.messages.get(...)
bodies = [msg['body'] for msg in resp['items']]
```

**Comment by prawn-cake** [comment]
@Ahellko, у объекта [Post](https://vk.com/dev/objects/post) есть поле `is_pinned`. Я не смог найти в документации vk api такого фильтра, но могу предположить, что когда вызываешь метод https://vk.com/dev/wall.get с `offset` 0, то первыми вернутся закрепленные посты. Это лишь предположение, не проверял.

**Comment by Ahellko** [comment]
@prawn-cake да так и есть, нулевой offset это либо закрепленный пост если есть, либо последний.

**Comment by prawn-cake** [comment]
@Ahellko , да, мне тоже казалось это логичным. Ну вот, тогда твоя проверка есть ли в группе закрепленные посты сводится к тому чтобы получить последнее сообщение со стены и проверить `is_pinned` свойство.

**Comment by prawn-cake** [comment]
Думаю, что вопрос закрыт.
