### ISSUE TITLE
Подскажите, как узнать количество участников беседы

### ISSUE THREAD

**Issue by RussianButman** [prawn-cake/vk-requests#22]

**Comment by prawn-cake** [comment]
Рекомендую всегда смотреть API документацию вк: https://vk.com/dev/methods
По вашему вопросу там например есть следующие методы которые точно будут полезны:
* https://vk.com/dev/messages.getChat (+ https://vk.com/dev/chat_object)
* https://vk.com/dev/messages.getChatUsers

Ну а вызов этих методов с помощью библиотеки очень прост, например, следуя README
```
api = vk_requests.create_api(..., scope=['offline', 'messages'], ...)
resp = api.messages.getChat(chat_id=12345)
print(resp)
```
можно получить нужную информацию
