### ISSUE TITLE
[question] как работать с long pool через данную библиотеку?

### ISSUE THREAD

**Issue by steamlinux** [prawn-cake/vk-requests#23]
https://vk.com/dev/using_longpoll
будьте добры, поделитесь примером работы с этой апи
а то постоянно каждые n секунд проверять наличие новых сообщений не очень рационально

**Comment by prawn-cake** [comment]
Честно говоря не проверял даже данную функциональность. Но судя по документации, данная фича весьма узконаправленная (применима только для сообщений) и не требует как таковой поддержки со стороны библиотеки.

Реализовать long-polling сообщений вручную выглядит простым, например, я бы попробовал сделать так
```
import requests
...

api = API(..., scope=['messages'])
resp = api.messages.getLongPollServer()
ts = resp['ts']

while TheTimeYouWannaPollFor:
    url = "https://{server}?act=a_check&key){key}&ts){ts}&wait=25&mode=2&version=1".format(**resp.update({'ts': ts}))
    resp = requests.get(url)
    updates, ts = resp['updates'], resp['ts']
```

Если вы упираетесь в лимит обращений к API в секунду, тогда имеет смысл оптимизировать, в обратном случае - нет, и лучше постоянно проверять каждые n секунд, библиотека по-умолчанию использует keep-alive HTTP сессии

**Comment by steamlinux** [comment]
спасибо за быстрый ответ, но у меня не получается
https://{$server}?act=a_check&key={$key}&ts={$ts}&wait=25&mode=2&version=2 
когда открываю эту ссылку (разумеется, со значениями) в браузере, все показывает как надо, а через метод requests.get(url) получаю ответ
[code]<Response [200]>[/code]
не подскажете, почему так? собственно, ошибка возникает на строке
[code]updates, ts = resp['updates'], resp['ts'][/code]
т.к. в ответе нет никаких 'updates' и 'ts'

**Comment by prawn-cake** [comment]
Все верно, потому что возвращается объект `Response`.
Я допустил неточность в своем примере, т.к по памяти писал. Там должен быть еще вызов `.json()` для response объекта.
Если вы до этого не работали с `requests`, то советую посмотреть [официальную документацию](http://docs.python-requests.org/en/master/)

**Comment by steamlinux** [comment]
огромное спасибо, все как надо заработало
теперь вместо проверки каждые 5 сек бот ждет сообщения и отвечает мгновенно:)
P.S. не публичный бот, для личного использования
