### ISSUE TITLE
vk-requests with proxy

### ISSUE THREAD

**Issue by NinoZombie** [prawn-cake/vk-requests#24]
Привет!
Спасибо еще раз за классную библиотеку!
Не могу понять:
можно ли залогиниться через прокси? и как это сделать?

Мне нужно прогнать 3 аккаунта, чтобы они залогинились каждый через свою прокси и сделали репост записи со стены сообщества себе.
Благодарю за помощь!

**Comment by prawn-cake** [comment]
Через библиотеку, к сожалению, сейчас нет такой поддержки, хотя там используется `requests`.
Но можно обойти это ограничение глобально, например, в linux, выставив переменную окружения [HTTP_PROXY](https://unix.stackexchange.com/questions/233810/proxy-all-requests-linux), т.е как-нибудь так:
`http_proxy=http://user:password@proxyserver.com:3128 python my_script.py`

А вообще, по-хорошему, надо добавить поддержку в библиотеку.

**Comment by NinoZombie** [comment]
Спасибо за ответ!
В итоге решил с помощью переназначения в цикле
os.environ['http_proxy']="http://user:password@proxyserver.com:3128" 
прямо в коде приложения.
