### ISSUE TITLE
Проблема с капчей.

### ISSUE THREAD

**Issue by feddorra** [prawn-cake/vk-requests#29]
Библиотека даёт ссылку (https://m.vk.com/captcha.php?s=0&sid=6Le00B8TAAAAACHiybbHy8tMOiJhM5vh88JVtP4c) на нерабочую картинку капчи.
![image](https://user-images.githubusercontent.com/32935793/34327634-266a73de-e8d2-11e7-9fb2-30839b55f528.png)
Если память не подводит, то параметр sid должен состоять только из цифр.

**Comment by prawn-cake** [comment]
Параметр sid (session_id) точно не может состоять только из цифр.
Пробовали использовать [service token](https://github.com/prawn-cake/vk-requests#using-service-token) вместо логина?

**Comment by prawn-cake** [comment]
@hdk5 спасибо за анализ и совет по решению!
Я проверю это.

**Comment by prawn-cake** [comment]
Fixed in [1.1.2](https://github.com/prawn-cake/vk-requests/tree/1.1.2)
