### ISSUE TITLE
[not bug] странность: один и тот-же скрипт работает на пк и не работает на вдс

### ISSUE THREAD

**Issue by steamlinux** [prawn-cake/vk-requests#31]
подскажите, пожалуйста. как возможно такое? рабочий скрипт без изменений копирую на вдс, запускаю так-же и на вдс он ругается на авторизацию
ошибка такая
```raise vk_error
vk_requests.exceptions.VkAPIError: error_code=5,message='User authorization failed: no access_token passed.',request_params={u'oauth': u'1', u'count': u'1', u'method': u'messages.get', u'service_token': u'6b...fc', u'v': u'5.45'}
```

код такой
п.с. long_key это ключ апи от группы, скрипт обрабатывает сообщения в группе
```
import vk_requests

long_key='6b...38fc'
api = vk_requests.create_api(service_token=long_key)
counts=api.messages.get(count=1)
```
на пк Debian Sid, на вдс debian jessie
библиотеку vk-requests пробовал обновить, и тут и там одинаковая версия

**Comment by steamlinux** [comment]
неделю бился, а через 5 минут после обращения разобрался
простите

**Comment by prawn-cake** [comment]
:+1:
