### ISSUE TITLE
How can I use client_secret for authorization?

### ISSUE THREAD

**Issue by proninyaroslav** [prawn-cake/vk-requests#37]
Hi. I want to use direct authorization (maybe Client Credentials Flow) for my application, that is, use the `client_secret` and application ID for authorization. How can I transfer the secret key by `vk_requests`? Or `vk_reuqests` doesn't support this type of authorization?

**Comment by prawn-cake** [comment]
Hi @proninyaroslav 
vk-requests implements 2 types of authorization:
1. [Oauth authorization code flow](https://vk.com/dev/authcode_flow_user)
2. Using [service token](https://vk.com/dev/service_token).  ([how to use](https://prawn-cake.github.io/vk-requests/#using-service-token))

Not sure what you mean by client credentials flow

**Comment by proninyaroslav** [comment]
About this https://vk.com/dev/auth_direct

**Comment by prawn-cake** [comment]
Hm, no, it's not supported unfortunately.
However looking at the call flow, it looks very similar to what it does for the current methods. 
So I guess it's shouldn't be a big deal to implement it.

**Comment by proninyaroslav** [comment]
Excellent. Do you need help in implementing this feature?

**Comment by prawn-cake** [comment]
I'd actually appreciate any help, because recently don't have much time for the new features.

**Comment by proninyaroslav** [comment]
I sent a patch that adds this feature.

**Comment by prawn-cake** [comment]
The feature is available in [v1.2.0](https://github.com/prawn-cake/vk-requests/tree/1.2.0).
