### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections'

### ISSUE THREAD

**Issue by vol1ura** [prawn-cake/vk-requests#41]
`lib/python3.8/site-packages/vk_requests/utils.py:3`: **DeprecationWarning**: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
```python    
from collections import Iterable
```
Update module please.

**Comment by prawn-cake** [comment]
@vol1ura feel free to contribute and send a pull-request =)

**Comment by prawn-cake** [comment]
Thanks for your contribution @vol1ura 

New update is available in the version 1.2.1
https://pypi.org/project/vk-requests/
