### ISSUE TITLE
Метод execute возвращает None

### ISSUE THREAD

**Issue by Thisman** [prawn-cake/vk-requests#5]
Использую хранимые процедуры на стороне сервера
VkScript ( `get_dialogs_count `)

`var dialogs = API.messages.getDialogs();
return dialogs["count"];`

При тестировании в песочнице VK, метод возвращает количество диалогов

Но если использовать обращение к этому методу через библиотеку
`dialogs_count = api.execute.get_dialogs_count()`
Возвращается `None`

При этом, если заменить в хранимой процедуре возвращаемое значение с `dialogs["count"]` на `dialogs` ответ приходит правильный. 
Это косяк со стороны VK? Или со стороны библиотеки?

**Comment by prawn-cake** [comment]
Из последнего абзаца очевидно, что проблема на стороне vk.

Твоя отладка наводит на мысль, что VKScript неверно выполняет получение значения по ключу из js объекта.

Я тоже столкнулся с подобной проблемой в другом контексте, сообщил о ней в тех.поддержку, они ее подтвердили, точнее подтвердили что я делаю все правильно, передали запрос разработчикам, а там тишина.

**Comment by Thisman** [comment]
Да, действительно проблема со стороны VK
