### ISSUE TITLE
Error in access permissions

### ISSUE THREAD

**Issue by stalkash** [prawn-cake/vk-requests#6]
The permit is only for the last item in the list "scope"
Example:
`"api = vk_requests.create_api(..., scope=[ 'messages','wall'], api_version='5.45')`
Requests to api.message.*  fail access like this:

> _raise vk_error
> vk_requests.exceptions.VkAPIError: error_code=15, message='Access denied: no access to call this method', request_params={'method': 'messages.getHistory', 'oauth': '1', 'user_id': '{my_id}', 'offset': '0', 'count': '200'}_

If I change to `scope=['wall, 'message']` : it all works fine, but api.wall.* failed.

**Comment by prawn-cake** [comment]
Confirm the problem. It will be fixed soon
As a workaround you can pass scope as a string, like `scope='messages, wall'`, but since next release it will work as expected.
Thanks for reporting

**Comment by prawn-cake** [comment]
Fixed in [v0.9.2](https://github.com/prawn-cake/vk-requests/tree/0.9.2)
