### ISSUE TITLE
Use api_version in all requests by default

### ISSUE THREAD

**Issue by irpab** [prawn-cake/vk-requests#9]
Now version specified in vk_requests.create_api(..., api_version='5.45') or default version is not used in API requests (only in authorization). So to make requests working properly it's necessary to specify version in each request or in default args for requests: vk_requests.create_api(..., api_version='5.45', **v='5.45'**).
It's ok but it'll be more straightforward to use version from api_version by default for API requests.

**Comment by prawn-cake** [comment]
Totally agree. I'll fix it soon. 
Or can you make PR for unittests dev branch spotting this case?

Anyway thanks for reporting.

**Comment by prawn-cake** [comment]
[fixed at v0.9.5](https://github.com/prawn-cake/vk-requests/tree/0.9.5)
